// export { default as Home } from "./Home/Home";
// export { default as Creativeprod } from "./CreativeSection/Creativeprod";
// export { default as ProudProducts } from "./OurProudProducts/ProudProducts";
// export { default as Trending } from "./Trending/Trending";
// export { default as ComfortableSec } from "./ComftableSec/ComfortableSec";
export { default as Home } from "./Home/Home";
export { default as CreativeProduct } from "./CreativeSection/CreativeProduct";
export { default as ProudProducts } from "./OurProudProducts/ProudProducts";
export { default as Trending } from "./Trending/Trending";
export { default as ComfortableSection } from "./ComfortableSection/ComfortableSection";
